old-new-game/arx/hinfiler/arxiv/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'web'], function () {
    Route::get('/', ['uses' => 'FrontController@index', 'as' => 'home']);
    Route::get('/start-game', ['uses' => 'FrontController@start_game', 'as' => 'start-game']);
    Route::get('/leaders-page', ['uses' => 'FrontController@show_leaders', 'as' => 'leaders-page']);
    Route::get('/regulations-page', ['uses' => 'FrontController@show_regulations', 'as' => 'regulations-page']);
    Route::any('/score-page', ['uses' => 'FrontController@show_score', 'as' => 'score-page']);
    Route::auth();
});



Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    // Admin home controller
    Route::resource('/dashboard', 'Admin\HomeController');

    // Questions controller
    // Get trash
    Route::get('/question/all-trash', 'Admin\QuestionController@get_trashed_questions')->name('question.all_trash');
    // Restore in trash
    Route::get('/question/restore/{id}', 'Admin\QuestionController@restore')->name('question.restore');
    // Final trash
    Route::post('/question/final-remove/{id}', 'Admin\QuestionController@final_remove')->name('question.final_remove');
    Route::resource('/question', 'Admin\QuestionController');
    // Questions controller

    // Answer controller
    Route::resource('/answer', 'Admin\AnswerController');
    // Answer controller

    // Collect questionnaire
    Route::resource('/questionnaire', 'Admin\QuestionnaireController');
    // Collect questionnaire
});



Auth::routes();

old-new-game/arx/hinfiler/arxiv/resources/views/admin/answer-add.blade.php
@extends('layouts.app')

@section('title', 'Add answer')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('answer.index') }}">Answers</a>
        </li>
        <li class="breadcrumb-item active">Add answer</li>
    </ol>
    <div class="row">
        <div class="col-sm-12">
            <form action="{{ route('answer.store') }}" method="post" enctype="multipart/form-data" id="add_answers">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="question">Question</label>
                    <select name="question" class="form-control custom-select" id="question">
                        <option selected>Select question</option>
                        @if(isset($unanswered_questions) && is_array($unanswered_questions))
                            @foreach($unanswered_questions as $question)
                                <option value="{{ $question->id }}">{{ $question->question }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-9">
                        <div class="form-group">
                            <label for="answer1">Answer 1</label>
                            <input type="text" name="answer1" value="{{ old('answer1') }}" class="form-control" id="answer1" placeholder="Answer 1 ...">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <div class="form-group">
                            <label>Poster</label>
                            <br>
                            <label for="answer1_img" class="btn btn-success">
                                Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                            </label>
                            <input type="file" name="images1" class="form-control-file" hidden id="answer1_img">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-1">
                        <div class="form-group">
                            <label>True</label>
                            <div class="custom-control custom-radio">
                                <input type="radio" value="answer1" id="customRadio1" name="truth" class="custom-control-input">
                                <label class="custom-control-label" for="customRadio1"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-9">
                        <div class="form-group">
                            <label for="answer2">Answer 2</label>
                            <input type="text" name="answer2" value="{{ old('answer2') }}" class="form-control" id="answer2" placeholder="Answer 2 ...">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <div class="form-group">
                            <label>Poster</label>
                            <br>
                            <label for="answer2_img" class="btn btn-success">
                                Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                            </label>
                            <input type="file" name="images2" class="form-control-file" hidden id="answer2_img">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-1">
                        <div class="form-group">
                            <label>True</label>
                            <div class="custom-control custom-radio">
                                <input type="radio" value="answer2" id="customRadio2" name="truth" class="custom-control-input">
                                <label class="custom-control-label" for="customRadio2"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-9">
                        <div class="form-group">
                            <label for="answer3">Answer 3</label>
                            <input type="text" name="answer3" value="{{ old('answer3') }}" class="form-control" id="answer3" placeholder="Answer 3 ...">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <div class="form-group">
                            <label>Poster</label>
                            <br>
                            <label for="answer3_img" class="btn btn-success">
                                Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                            </label>
                            <input type="file" name="images3" class="form-control-file" hidden id="answer3_img">
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-1">
                        <div class="form-group">
                            <label>True</label>
                            <div class="custom-control custom-radio">
                                <input type="radio" value="answer3" id="customRadio3" name="truth" class="custom-control-input">
                                <label class="custom-control-label" for="customRadio3"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success btn-block" id="add-answer">
                    Add answer
                </button>
            </form>
        </div>
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/answer-list.blade.php
@extends('layouts.app')

@section('title', 'Answer list')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Answers</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-12 col-md-10">
                    <label>
                        <select class="form-control custom-select">
                            <option selected>Select question</option>
                            @if(isset($questions) && is_array($questions))
                                @foreach($questions as $key => $question)
                                    <option value="{{ $key }}">{{ $question }}</option>
                                @endforeach
                            @endif
                        </select>
                    </label>
                </div>
                <div class="col-sm-12 col-md-2">
                    <a href="{{ route('answer.create') }}" role="button" class="btn btn-success float-right btn-sm">
                        Add new answer &nbsp;
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Question</th>
                        <th>Answer</th>
                        <th>Images</th>
                        <th>Truth</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(isset($answers) && is_object($answers))
                        @foreach($answers as $key => $answer)
                            @if (($key % 3) === 0)
                                <tr>
                                    <td>{{ $answer->id }}</td>
                                    <td>{{ $answer->question->question }}</td>
                                    <td>{{ $answer->answer }}</td>
                                    <td>
                                        <img src="{{ asset('images') . '/' . $answer->answer_photo }}" alt="Answer{{ $answer->id }}" width="50">
                                    </td>
                                    <td>
                                        <button type="button" class="btn {{ $answer->truth ? 'btn-success' : 'btn-danger' }}">
                                            <i class="fa {{ $answer->truth ? 'fa-check' : 'fa-times' }} fa-fw"></i>
                                        </button>
                                    </td>
                                    <td>
                                        {{-- update --}}
                                        <a href="{{ route('answer.edit', ['id' => $answer->id]) }}" role="button" class="btn btn-outline-info btn-sm">
                                            Edit <i class="fa fa-edit"></i>
                                        </a>
                                        {{-- update --}}
                                    </td>
                                    <td>
                                        {{-- Send to trash --}}
                                        <form action="{{ route('answer.destroy', $answer->id) }}" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button class="btn btn-outline-danger btn-sm">Send to trash <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                        {{-- Send to trash --}}
                                    </td>
                                </tr>
                            @else
                                <tr>
                                    <td>{{ $answer->id }}</td>
                                    <td>{{ $answer->question->question }}</td>
                                    <td>{{ $answer->answer }}</td>
                                    <td>
                                        <img src="{{ asset('images') . '/' . $answer->answer_photo }}" alt="Answer{{ $answer->id }}" width="50">
                                    </td>
                                    <td>
                                        <button type="button" class="btn {{ $answer->truth ? 'btn-success' : 'btn-danger' }}">
                                            <i class="fa {{ $answer->truth ? 'fa-check' : 'fa-times' }} fa-fw"></i>
                                        </button>
                                    </td>
                                    <td>
                                        {{-- update --}}
                                        <a href="{{ route('answer.edit', ['id' => $answer->id]) }}" role="button" class="btn btn-outline-info btn-sm">
                                            Edit <i class="fa fa-edit"></i>
                                        </a>
                                        {{-- update --}}
                                    </td>
                                    <td>
                                        {{-- Send to trash --}}
                                        <form action="{{ route('answer.destroy', $answer->id) }}" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button class="btn btn-outline-danger btn-sm">Send to trash <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                        {{-- Send to trash --}}
                                    </td>
                                </tr>
                            @endif
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
            <div class="float-right">
                @if(isset($answers) && is_object($answers))
                    {{ $answers->links() }}
                @endif
            </div>
        </div>
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

old-new-game/arx/hinfiler/arxiv/resources/views/admin/question-add.blade.php
@extends('layouts.app')

@section('title', 'Add question')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('question.index') }}">Questions</a>
        </li>
        <li class="breadcrumb-item active">Add question</li>
    </ol>
    <div class="col-sm-12 col-md-8 offset-2">
        <form action="{{ route('question.store') }}" method="post">
            {{ csrf_field() }}
            <div class="form-group">
                <label for="question">Question</label>
                <input type="text" name="question" value="{{ old('question') }}" class="form-control" id="question" placeholder="Question text">
            </div>
            <div class="form-group">
                <label for="score">Score</label>
                <input type="text" name="score" value="{{ old('score') }}" class="form-control" id="score" placeholder="Score">
            </div>
            <br>
            <button type="submit" class="btn btn-success btn-block">Add question</button>
        </form>
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/question-edit.blade.php
@extends('layouts.app')

@section('title', 'Edit question')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('question.index') }}">Questions</a>
        </li>
        <li class="breadcrumb-item active">Edit question</li>
    </ol>
    <div class="col-sm-12 col-md-8 offset-2">
        @if(isset($question) && is_object($question))
        <form action="{{ route('question.update', ['id' => $question->id]) }}" method="post">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="question">Question</label>
                <input type="text" name="question" value="{{ $question->question }}" class="form-control" id="question" placeholder="Question text">
            </div>
            <div class="form-group">
                <label for="score">Score</label>
                <input type="text" name="score" value="{{ $question->score }}" class="form-control" id="score" placeholder="Score">
            </div>
            <br>
            <button type="submit" class="btn btn-success btn-block">Update question</button>
        </form>
        @endif
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/question-list.blade.php
@extends('layouts.app')

@section('title', 'Question list')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Questions</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <label>Show
                <select class="form-control-sm custom-select" style="width: 70px;">
                    <option selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                entries</label>
            <a href="{{ route('question.create') }}" role="button" class="btn btn-success float-right btn-sm">
                Add new question &nbsp;
                <i class="fa fa-plus"></i>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Question</th>
                        <th>Score</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Edit</th>
                        <th>Add to trash</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(isset($questions) && is_object($questions))
                        @foreach($questions as $question)
                    <tr>
                        <td>{{ $question->id }}</td>
                        <td>{{ $question->question }}</td>
                        <td>{{ $question->score }}</td>
                        <td>{{ \Carbon\Carbon::parse($question->created_at)->format('d.m.Y') }}</td>
                        <td>{{ \Carbon\Carbon::parse($question->created_at)->format('d.m.Y') }}</td>
                        <td>
                            {{-- update --}}
                            <a href="{{ route('question.edit', ['id' => $question->id]) }}" role="button" class="btn btn-outline-info btn-sm">
                                Edit <i class="fa fa-edit"></i>
                            </a>
                            {{-- update --}}
                        </td>
                        <td>
                            {{-- Send to trash --}}
                            <form action="{{ route('question.destroy', $question->id) }}" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-outline-danger btn-sm">Send to trash <i class="fa fa-trash"></i>
                                </button>
                            </form>
                            {{-- Send to trash --}}
                        </td>
                    </tr>
                    @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
            <div class="float-right">
                @if(isset($questions) && is_object($questions))
                    {{ $questions->links() }}
                @endif
            </div>
        </div>
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/questionnaire-add.blade.php
@extends('layouts.app')

@section('title', 'Questionnaire add')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('questionnaire.index') }}">Questionnaires</a>
        </li>
        <li class="breadcrumb-item active">Questionnaire add</li>
    </ol>
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card">
                        <h5 class="card-header">
                            Questionnaire
                            <span class="text-right text-danger" style="font-size: 14px; margin-bottom: 0;">
                                ( Hold the mouse and drag questions to this block. <i class="fa fa-hand-o-down"></i> )
                            </span>
                        </h5>
                        <div id="sortable1" class="card-body connectedSortable">
                            <form action="{{ route('questionnaire.store') }}" method="post" id="question-form">
                                {{ @csrf_field() }}
                                <input type="hidden" id="question-id-form" name="questions_id[]" value="">
                            </form>
                        </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control" name="title" form="question-form" placeholder="Enter questionnaire title">
                    </div>
                    <button type="submit" form="question-form" class="btn btn-outline-success">Save questionnaire</button>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <h5 class="card-header">Questions</h5>
                        <div id="sortable2" class="card-body connectedSortable">
                            @if (isset($questions) && is_object($questions))
                                @foreach($questions as $question)
                                    @if(!$question->answers->isEmpty())
                                        <div class="alert alert-success" id="{{ $question->id }}" role="alert" style="padding: 5px; font-size: 14px;">
                                            {{ $question->question }}
                                        </div>
                                    @endif
                                @endforeach
                            @endif
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

old-new-game/arx/hinfiler/arxiv/resources/views/admin/questionnaire-list.blade.php
@extends('layouts.app')

@section('title', 'Questionnaire list')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('dashboard.index') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Questionnaire</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <label>Show
                <select class="form-control-sm custom-select" style="width: 70px;">
                    <option selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                entries</label>
            <a href="{{ route('questionnaire.create') }}" role="button" class="btn btn-success float-right btn-sm">
                Collect a new questionnaire
                <i class="fa fa-plus"></i>
            </a>
        </div>
        <div class="card-body">

            <div class="accordion" id="accordion">
                @if(isset($new_questionnaires) && is_array($new_questionnaires))
                    @foreach($new_questionnaires as $key => $questionnaire)
                        <div class="card">
                            <div class="card-header">
                                <h5 class="mb-0">
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{ $questionnaire['id'] }}" aria-expanded="true" aria-controls="collapseOne">
                                        <h5>{{ $questionnaire['id'] }} &nbsp; {{ $questionnaire['title'] }} &nbsp; {{ \Carbon\Carbon::parse($questionnaire['created_at'])->format('d / m / Y') }}</h5>
                                    </button>
                                </h5>
                            </div>
                            <div id="collapse{{ $questionnaire['id'] }}" class="collapse {{ $key ? '' : 'show' }}" data-parent="#accordion">
                                @foreach($questionnaire['questions'] as $question)
                                    <div class="table-responsive">
                                        <table class="table" style="margin-bottom: 0;">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">{{ $question->question }}</th>
                                            </tr>
                                            </thead>
                                        </table>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Answer</th>
                                                <th scope="col">Answer photo</th>
                                                <th scope="col">Truth</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($question->answers as $answer)
                                                <tr>
                                                    <th>{{ $answer->id }}</th>
                                                    <td><b>{{ $answer->answer }}</b></td>
                                                    <td><img src="{{ asset('images') . '/' . $answer->answer_photo }}" width="50" height="50" alt="$answer->answer_photo"></td>
                                                    <td>
                                                        <button class="btn {{ ($answer->truth) ? 'btn-success' : 'btn-danger' }} btn-sm">
                                                            <i class="fa {{ ($answer->truth) ? 'fa-check' : 'fa-times' }} fa-fw"></i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection