old-new-game/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'FrontController@index', 'as' => 'home']);

Route::group(['middleware' => ['auth', 'gameTime']], function () {
    Route::get('/start-page', ['uses' => 'FrontController@start_page', 'as' => 'start-page']);
    Route::get('/game-start', ['uses'=>'FrontController@start', 'as'=>'game-start']);
    Route::post('/ajax-call', ['uses' => 'FrontController@ajax_call', 'as' => 'ajax-call']);
    Route::post('/save-result', ['uses' => 'FrontController@save_result', 'as' => 'save-result']);
    Route::get('/score-page', ['uses' => 'FrontController@show_score', 'as' => 'score-page']);
    Route::get('/leaders-page', ['uses' => 'FrontController@show_leaders', 'as' => 'leaders-page']);
    Route::get('/regulations-page', ['uses' => 'FrontController@regulations', 'as' => 'regulations-page']);
});

// Admin
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role', 'gameTime']], function () {
    // Dashboard
    Route::get('/home', 'Admin\HomeController@index')->name('admin.dashboard');
    // Questions
    // Restore in trash
    Route::get('/question/restore/{id}', 'Admin\QuestionController@restore')->name('question.restore');
    // Final delete
    Route::post('/question/final-remove/{id}', 'Admin\QuestionController@final_remove')->name('question.final_remove');
    // Show all trashed question
    Route::get('/question-in-trash', 'Admin\QuestionController@get_trashed_questions')->name('question.in-trash');
    // Send trash question and answers
    Route::any('/check-answers', 'Admin\QuestionController@check_isset_answers')->name('question.check-answers');
    Route::resource('/question', 'Admin\QuestionController');
    // Collect questionnaire
    Route::resource('/questionnaire', 'Admin\QuestionnaireController');
    // User list
    Route::resource('/user', 'Admin\UserController');
});
// Admin
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

old-new-game/resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="admin-dashboard">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Dashboard</div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif

                            You are logged in!
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

old-new-game/resources/views/admin/question-add.blade.php
@extends('layouts.app')

@section('title', 'Add question')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('question.index') }}">Questions</a>
        </li>
        <li class="breadcrumb-item active">Add question</li>
    </ol>
    <div class="col-sm-12 col-md-10 offset-1">
        <form action="{{ route('question.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{-- Question --}}
            <div class="form-group">
                <label for="question">Question</label>
                <input type="text" name="question" value="{{ old('question') }}" class="form-control" id="question" placeholder="question text">
            </div>
            {{-- Score --}}
            <div class="form-group">
                <label for="score">Score</label>
                <input type="text" name="score" value="{{ old('score') }}" class="form-control" id="score" placeholder="question score">
            </div>
            <br>
            <hr>
            <br>
            {{-- Answer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer1" value="{{ old('answer1') }}" class="form-control" placeholder="variants of answers...">
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer1_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images1" class="form-control-file" hidden id="answer1_img">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer1" id="customRadio1" name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio1" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {{-- Aswer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer2" value="{{ old('answer2') }}" class="form-control" placeholder="variants of answers...">
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer2_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images2" class="form-control-file" hidden id="answer2_img">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer2" id="customRadio2" name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio2" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {{-- Answer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer3" value="{{ old('answer3') }}" class="form-control" placeholder="variants of answers...">
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer3_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images3" class="form-control-file" hidden id="answer3_img">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer3" id="customRadio3" name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio3" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {{-- Button --}}
            <button type="submit" class="btn btn-success btn-block">
                Add question
            </button>
        </form>
    </div>
@endsection

old-new-game/resources/views/admin/question-edit.blade.php
@extends('layouts.app')

@section('title', 'Update question')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('question.index') }}">Questions</a>
        </li>
        <li class="breadcrumb-item active">Add question</li>
    </ol>
    <div class="col-sm-12 col-md-10 offset-1">
        <form action="{{ route('question.update', $question->id) }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            {{-- Question --}}
            <div class="form-group">
                <label for="question">Question</label>
                <input type="text" name="question" value="{{ $question->question }}" class="form-control" id="question" placeholder="question text">
            </div>
            {{-- Score --}}
            <div class="form-group">
                <label for="score">Score</label>
                <input type="text" name="score" value="{{ $question->score }}" class="form-control" id="score" placeholder="question score">
            </div>
            <br>
            <hr>
            <br>
            {{-- Answer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer1" value="{{ $answers[0]->answer }}" class="form-control" placeholder="variants of answers...">
                        <input type="hidden" name="answer1_id" value="{{ $answers[0]->id }}">
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer1_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images1" class="form-control-file" hidden id="answer1_img">
                        <input type="hidden" name="old_images1" value="{{ $answers[0]->answer_photo }}">
                        <img src="{{ asset('images') . '/' . $answers[0]->answer_photo }}" alt="{{ $answers[0]->answer_photo }}" style="width: 60px;height: 50px;margin-left: 5px;">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer1" id="customRadio1" {{ ($answers[0]->truth) ? 'checked' : '' }} name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio1" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>

            {{-- Aswer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer2" value="{{ $answers[1]->answer }}" class="form-control" placeholder="variants of answers...">
                        <input type="hidden" name="answer2_id" value="{{ $answers[1]->id }}">

                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer2_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images2" class="form-control-file" hidden id="answer2_img">
                        <input type="hidden" name="old_images2" value="{{ $answers[1]->answer_photo }}">
                        <img src="{{ asset('images') . '/' . $answers[1]->answer_photo }}" alt="{{ $answers[1]->answer_photo }}" style="width: 60px;height: 50px;margin-left: 10px;">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer2" id="customRadio2" {{ ($answers[1]->truth) ? 'checked' : '' }} name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio2" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>

            {{-- Answer --}}
            <div class="row">
                <div class="col-sm-12 col-md-9">
                    <div class="form-group">
                        <input type="text" name="answer3" value="{{ $answers[2]->answer }}" class="form-control" placeholder="variants of answers...">
                        <input type="hidden" name="answer3_id" value="{{ $answers[2]->id }}">
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group">
                        <label for="answer3_img" class="btn btn-success">
                            Choose <span class="img-count">...</span> <i class="fa fa-upload"></i>
                        </label>
                        <input type="file" name="images3" class="form-control-file" hidden id="answer3_img">
                        <input type="hidden" name="old_images3" value="{{ $answers[2]->answer_photo }}">
                        <img src="{{ asset('images') . '/' . $answers[2]->answer_photo }}" alt="{{ $answers[2]->answer_photo }}" style="width: 60px;height: 50px;margin-left: 10px;">
                    </div>
                </div>
                <div class="col-sm-12 col-md-1">
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <input type="radio" value="answer3" id="customRadio3" {{ ($answers[2]->truth) ? 'checked' : '' }} name="truth" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio3" style="display: inherit;"></label>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {{-- Button --}}
            <button type="submit" class="btn btn-success btn-block">
                Update question
            </button>
        </form>
    </div>
@endsection

old-new-game/resources/views/admin/question-list.blade.php
@extends('layouts.app')

@section('title', 'Question list')

@section('content')
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{{ route('admin.dashboard') }}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Questions</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <label>Show
            <select class="form-control-sm custom-select" style="width: 70px;">
                <option selected>10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            entries</label>
        <a href="{{ route('question.create') }}" role="button" class="btn btn-success float-right btn-sm">
            Add new question &nbsp;
            <i class="fa fa-plus"></i>
        </a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Question</th>
                    <th>Score</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>Edit</th>
                    <th>Add to trash</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($questions) && is_object($questions))
                @foreach($questions as $question)
                <tr>
                    <td>{{ $question->id }}</td>
                    <td>{{ $question->question }}</td>
                    <td>{{ $question->score }}</td>
                    <td>{{ \Carbon\Carbon::parse($question->created_at)->format('d.m.Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($question->created_at)->format('d.m.Y') }}</td>
                    <td>
                        {{--update--}}
                        <a href="{{ route('question.edit', ['id' => $question->id]) }}" role="button" class="btn btn-outline-info btn-sm">
                            Edit <i class="fa fa-edit"></i>
                        </a>
                        {{--update--}}
                    </td>
                    <td>
                        {{-- Send to trash --}}
                        <form action="{{ route('question.destroy', $question->id) }}" method="post" id="{{ $question->id }}" class="question_trash_form">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="question_id" value="{{ $question->id }}">
                            <button class="btn btn-outline-danger btn-sm">Send to trash <i class="fa fa-trash"></i>
                            </button>
                        </form>
                        {{-- Send to trash --}}
                    </td>
                </tr>
                @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <div class="float-right">
            @if(isset($questions) && is_object($questions))
            {{ $questions->links() }}
            @endif
        </div>
    </div>
</div>
{{-- Answers modal --}}
<div class="modal fade bd-example-modal-lg" id="answers-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Answers related to this question <span class="text-danger">(they will also be sent to trash)</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered table-hover" id="related_answers" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Question</th>
                        <th>Images</th>
                        <th>Truth</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="data-trash-button" form="">I agree</button>
            </div>
        </div>
    </div>
</div>
{{-- Answers modal --}}
@endsection

old-new-game/resources/views/admin/questionnaire-add.blade.php
@extends('layouts.app')

@section('title', 'Questionnaire add')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('questionnaire.index') }}">Questionnaires</a>
        </li>
        <li class="breadcrumb-item active">Questionnaire add</li>
    </ol>
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card">
                        <h5 class="card-header">
                            Questionnaire
                            <span class="text-right text-danger" style="font-size: 14px; margin-bottom: 0;">
                                ( Hold the mouse and drag questions to this block. <i class="fa fa-hand-o-down"></i> )
                            </span>
                        </h5>
                        <div id="sortable1" class="card-body connectedSortable">
                            <form action="{{ route('questionnaire.store') }}" method="post" id="question-form">
                                {{ @csrf_field() }}
                                <input type="hidden" id="question-id-form" name="questions_id[]" value="">
                            </form>
                        </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control" name="title" form="question-form" placeholder="Enter questionnaire title">
                    </div>
                    <button type="submit" form="question-form" class="btn btn-outline-success">Save questionnaire</button>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <h5 class="card-header">Questions</h5>
                        <div id="sortable2" class="card-body connectedSortable">
                            @if (isset($questions) && is_object($questions))
                                @foreach($questions as $question)
                                    @if(!$question->answers->isEmpty())
                                        <div class="alert alert-success" id="{{ $question->id }}" role="alert" style="padding: 5px; font-size: 14px;">
                                            {{ $question->question }}
                                        </div>
                                    @endif
                                @endforeach
                            @endif
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

old-new-game/resources/views/admin/questionnaire-list.blade.php
@extends('layouts.app')

@section('title', 'Questionnaire list')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Questionnaire</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <label>Show
                <select class="form-control-sm custom-select" style="width: 70px;">
                    <option selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                entries</label>
            <a href="{{ route('questionnaire.create') }}" role="button" class="btn btn-success float-right btn-sm">
                Collect a new questionnaire
                <i class="fa fa-plus"></i>
            </a>
        </div>
        <div class="card-body">

            <div class="accordion" id="accordion">
                @if(isset($new_questionnaires) && is_array($new_questionnaires))
                    @foreach($new_questionnaires as $key => $questionnaire)
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-link float-left" style="font-size: 18px;" type="button" data-toggle="collapse" data-target="#collapse{{ $questionnaire['id'] }}" aria-expanded="true" aria-controls="collapseOne">
                                    {{ $questionnaire['id'] }} &nbsp; {{ $questionnaire['title'] }} &nbsp; {{ \Carbon\Carbon::parse($questionnaire['created_at'])->format('d / m / Y') }}
                                </button>
                                <form action="{{ route('questionnaire.destroy', $questionnaire['id']) }}" id="delete_questionnaire{{ $questionnaire['id'] }}" onsubmit="return confirm('Are you sure ?');" method="post">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                </form>
                                <button type="submit" form="delete_questionnaire{{ $questionnaire['id'] }}" class="btn btn-danger btn-sm float-right">
                                    Delete questionnaire <i class="fa fa-window-close"></i>
                                </button>
                            </div>
                            <div id="collapse{{ $questionnaire['id'] }}" class="collapse {{ $key ? '' : 'show' }}" data-parent="#accordion">
                                @foreach($questionnaire['questions'] as $question)
                                    <div class="table-responsive">
                                        <table class="table" style="margin-bottom: 0;">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">{{ $question->question }}</th>
                                            </tr>
                                            </thead>
                                        </table>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Answer</th>
                                                <th scope="col">Answer photo</th>
                                                <th scope="col">Truth</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($question->answers as $answer)
                                                <tr>
                                                    <th>{{ $answer->id }}</th>
                                                    <td><b>{{ $answer->answer }}</b></td>
                                                    <td><img src="{{ asset('images') . '/' . $answer->answer_photo }}" width="50" height="50" alt="$answer->answer_photo"></td>
                                                    <td>
                                                        <button class="btn {{ ($answer->truth) ? 'btn-success' : 'btn-danger' }} btn-sm">
                                                            <i class="fa {{ ($answer->truth) ? 'fa-check' : 'fa-times' }} fa-fw"></i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection

old-new-game/resources/views/admin/user-list.blade.php
@extends('layouts.app')

@section('title', 'User list')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Users</li>
    </ol>
    <div class="card mb-3">
        {{--<div class="card-header">
            <label>Show
                <select class="form-control-sm custom-select" style="width: 70px;">
                    <option selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                entries</label>
            <a href="{{ route('question.create') }}" role="button" class="btn btn-success float-right btn-sm">
                Add new question &nbsp;
                <i class="fa fa-plus"></i>
            </a>
        </div>--}}
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Avatar</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Result</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(isset($user_arr) && is_array($user_arr))
                        @foreach($user_arr as $user)
                            <tr>
                                <td>{{ $user['id'] }}</td>
                                <td><img src="{{ $user['avatar'] }}" width="50" alt="{{ $user['avatar'] }}"></td>
                                <td>{{ $user['name'] }}</td>
                                <td>{{ $user['email'] }}</td>
                                <td>{{ $user['result'] }}</td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
            {{--<div class="float-right">
                @if(isset($questions) && is_object($questions))
                    {{ $questions->links() }}
                @endif
            </div>--}}
        </div>
    </div>
@endsection